### ISSUE TITLE
Experiment results provide

### ISSUE THREAD

**Issue by kai0416s** [mic-rud/Learned-Compression-of-Point-Cloud-Geometry-and-Attributes#1]
Thank you for your outstanding work!
Can you provide the test sequence excel result for D1-PSNR D2-PSNR Y-PSNR YUV-PSNR and 1-PCQM?

**Comment by mic-rud** [comment]
Thank you for your interest in our work. I uploaded the results to results/Ours/test.csv. 
Depending on your needs, these are the results over the cross product of all tested attribute qualities q_a and geoemtry qualities q_g. 

You can compute the pareto fronts for each tested point cloud or filter by the specified configuration for the rate points specified in the paper. The scripts in plot.py could help to serve as a boilerplate.

**Comment by kai0416s** [comment]
Thank you!!

**Comment by kai0416s** [comment]
Another question is that there are currently few unified methods, and I have also noticed their method from Yoga, but they haven't made their Excel results public. How did you obtain their results? Looking forward to your reply, thank you.
