### ISSUE TITLE
ModuleNotFoundError: No module named 'bitstream'

### ISSUE THREAD

**Issue by mayangzhi** [mic-rud/Learned-Compression-of-Point-Cloud-Geometry-and-Attributes#2]
Hello! Thank you for your excellent open-source work.
I have a trouble when trying to run this code as following: 
```
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    from model.model import ColorModel
  File "Learned-Compression-of-Point-Cloud-Geometry-and-Attributes-main/model/model.py", line 9, in <module>
    from bitstream import BitStream
ModuleNotFoundError: No module named 'bitstream'
```
I am wordering that is there a missing python file called 'bitstream'? Or should I install any extra package?
Look forward to your reply, wish you all the best!

**Comment by mic-rud** [comment]
Thank you for your interest and bringing this to our attention, you will need to install the package 

For now:
```
pip install bitstream
```

I will update the requirements.txt file in the coming days. Furthermore, I've notice that model weights are still missing. I will upload them aswell

**Comment by mayangzhi** [comment]
Really appreciate for your reply!
